name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - name: Fetch Repos
        run: npm run fetch-data ${{ github.actor }}
      - name: Build
        run: npm run build
        env:
          VITE_GITHUB_ACTOR: ${{ github.actor }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
